[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-9_x"]
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"