[variables]
NIXPACKS_NODE_VERSION = "23"
NIXPACKS_PKGS = "nodejs_23"

[phases.setup]
packages = ["nodejs_23", "curl", "wget"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
