name: 'Ingest: Tasks'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    # - cron: '0 * * * *' # Runs every hour, adjust to your needs
    - cron: '*/15 * * * *' # Run every 15 minutes
    # - cron: '30 * * * *' # Run every hour on the half-hour
    # - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger from the GitHub UI

env:
  INGEST_TOKEN: ${{ secrets.INGEST_TOKEN }}

jobs:
  run-update-posts:
    uses: ./.github/workflows/reusable-task-runner.yml
    with:
      task: update_posts
      token: ${{ secrets.INGEST_TOKEN }}

  run-update-popular-posts:
    uses: ./.github/workflows/reusable-task-runner.yml
    with:
      task: update_popular_posts
      token: ${{ secrets.INGEST_TOKEN }}